enabled: true
production-mode: true
grid-size: grid-md
header-fixed: true
header-animated: true
header-dark: true
header-transparent: true
sticky-footer: true
blog-page: /blog
spectre:
  exp: true
  icons: true
custom_logo: {  }
custom_logo_mobile: {  }
